# Generated by Django 6.0.4 on 2026-04-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
            ],
        ),
    ]
